name: ML CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: pytest tests/

    - name: Small-Scale Training
      run: python train.py

    - name: Evaluate Model
      run: python evaluate.py

    - name: Check Performance Threshold
      run: python check_performance.py

    - name: Upload Model Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: artifacts/

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Download Model Artifacts
      uses: actions/download-artifact@v4
      with:
        name: model-artifacts
        path: artifacts/

    - name: Deploy to Staging
      run: |
        echo "Deploying new model artifact..."
        echo "Model SHA: ${{ github.sha }}"
        echo "Copying model.pkl to staging environment..."
        ls -la artifacts/
        echo "Model size: $(du -h artifacts/model.pkl)"
        echo "Model successfully deployed to staging!"
        echo "Deployment timestamp: $(date)"