name: ML CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run Unit Tests
      run: pytest tests/

    - name: Small-Scale Training
      run: python train.py

    - name: Evaluate Model
      run: python evaluate.py

    - name: Check Performance Threshold
      run: python check_performance.py

    - name: Upload Model Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: artifacts/

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    
    - name: Download Model Artifacts
      uses: actions/download-artifact@v4
      with:
        name: model-artifacts
        path: artifacts/

    - name: Build Docker Image
      run: |
        echo "Building Docker image with model..."
        docker build -t myorg/ml-app:${{ github.sha }} .
        docker build -t myorg/ml-app:latest .

    - name: Build Docker Image
      run: |
        echo "Building Docker image with model..."
        docker build -t jhongda/ml-app:${{ github.sha }} .
        docker build -t jhongda/ml-app:latest .

    - name: Push to Docker Hub
      run: |
        echo "Pushing Docker image to Docker Hub..."
        docker push jhongda/ml-app:${{ github.sha }}
        docker push jhongda/ml-app:latest

    - name: Deploy to Staging
      run: |
        echo "Docker image pushed to Docker Hub!"
        echo "Image: jhongda/ml-app:${{ github.sha }}"
        echo "Available at: docker pull jhongda/ml-app:latest"